apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-webapp-nodejs
  name: sample-webapp-nodejs
  namespace: production
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sample-webapp-nodejs
  type: ClusterIP
